### ISSUE TITLE
How-To-Run problem on third instruction.

### ISSUE THREAD

**Issue by tiemfah** [wodwine/django-polls#3]
The new ".env" file contains [SECRET_KEY, DEBUG, ALLOWED_HOSTS, TIMEZONE] 
_**FYI: copy from your own ".env" file**_

if I copied my own .env file it wouldn't work because some lines are missing and it doesn't match with your .env (eg. empty .env file) and even if I know what to fill in .env file you did not specify what do I have to fill in.

**Comment by wodwine** [comment]
k

**Comment by wodwine** [comment]
OK I know the problems and I changed this one
